---
title: "S3 Sharing"
author: "Logan Harris"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: show
---

```{r setup, child = 'web/_include/setup.rmd'}
```

Shared bucket name:
loganharris.github.lasso-boot.rds

Following the idea here:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/example-walkthroughs-managing-access-example2.html

# For User under Account B

1. Set up user from root account using the IAM identity center
2. Have user log in and then select their desired role and follow the directions for `Command line or programmatic access`
3. Follow directions to use the recommended set up: https://docs.aws.amazon.com/cli/latest/userguide/sso-configure-profile-token.html#sso-configure-profile-token-auto-sso
  a. For simplicity, you may want to follow the `default` option.
4. Test `aws sso login`

# For Root Account Holder A (sharer of S3)
1. Create bucket
2. Add something to it (lasso-boot.pdf)
3. Attach policy:
```
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "share-bucket",
			"Effect": "Allow",
			"Principal": {
				"AWS": ["arn:aws:iam::391496244506:root"]
			},
			"Action": "s3:*",
			"Resource": [
				"arn:aws:s3:::test/*",
				"arn:aws:s3:::test"
			]
		}
	]
}
```

- May need to only specify account number?

# For Root Account Holder B (reciever of S3)


1. Delegate permissions to group through permission sets by adding an inline policy.
```
{
   "Version": "2012-10-17",
   "Statement": [
      {
         "Sid": "Example",
         "Effect": "Allow",
         "Action": [
            "s3:*"
         ],
         "Resource": [
            "arn:aws:s3:::test/*",
            "arn:aws:s3:::test"
         ]
      }
   ]
}
```

# Other Links
- https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/list-buckets.html
- https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_policy-examples.html#example-delegate-xaccount-S3

# Issue

Traceback (most recent call last):
  File "/opt/homebrew/bin/dat", line 8, in <module>
    sys.exit(dat())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dat.py", line 53, in dat
    elif arg['push']: dat_push(arg['-d'])
                      ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dat.py", line 460, in dat_push
    master = get_master(config, local)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dat.py", line 141, in get_master
    s3.create_bucket(Bucket=bucket)
  File "/Users/loganharris/Library/Python/3.11/lib/python/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/loganharris/Library/Python/3.11/lib/python/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.

