---
title: "EB CI Simple Example"
author: "Logan Harris"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Attempt 2 (Exactly the same)

- Here, I attempted to move things around so more of the computation was done on the log scale, but evidently these pieces didn't lead to any actual difference.

```{r}
density_function <- function(x, rate, mean, sigma, n = 30) {
    prior <- log(dlaplace(x, rate = rate))
    llik <- ll(beta = x, mean = mean, sigma = sigma, n = n)
    return(prior + llik)
}

density_function_normalized <- function(x, rate, mean, sigma, n = 30, normalizer) {
    prior <- log(dlaplace(x, rate = rate))
    llik <- ll(beta = x, mean = mean, sigma = sigma, n = n)
    return(exp(prior + llik - normalizer))  # Assuming `normalizer` is also in log space
}


integrate_exp <- function(lower, upper, rate, mean, sigma, n) {
    integrand <- function(x, rate, mean, sigma, n) exp(density_function(x, rate=rate, mean=mean, sigma=sigma, n=n))
    return(integrate(integrand, lower, upper, rate, mean, sigma, n))
}

obj_simple <- function(beta, post_mode, p, rate, mean, sigma, n = 30) {

  rng <- Inf
  denom <- integrate_exp(
    lower = post_mode-rng, upper = post_mode+rng, rate=rate, mean=mean, sigma=sigma, n=n
  )$value

  if (p > .5) {
    prob <- integrate(
      density_function_normalized, lower = post_mode, upper = beta,
      rate = rate, mean = mean, sigma = sigma, n = n,
      normalizer = log(denom)
    )$value
  } else {
    prob <- integrate(
      density_function_normalized, lower = beta, upper = post_mode,
      rate = rate, mean = mean, sigma = sigma, n = n,
      normalizer = log(denom)
    )$value
  }

  sig <- abs((1-2*p))
  return((sig/2) - prob)

}


post_quant <- function(conf, mean = 0, sigma = 1, rate = 1, n = 30) {
  
  
  xvals <- seq(-3, 3, by = .1)
  yvals <- density_function(xvals, rate, mean, sigma, n)
  post_mode <- xvals[which.max(yvals)]
  
  rng <- Inf
  denom <- integrate_exp(
    lower = post_mode-rng, upper = post_mode+rng, rate=rate, mean=mean, sigma=sigma, n=n
  )$value
  print(denom)
  
  yvals <- density_function_normalized(xvals, rate, mean, sigma, n, log(denom))
  post_mode <- xvals[which.max(yvals)]
  
  ## Check
  print(integrate(
      density_function_normalized, lower = -rng, upper = rng,
      rate = rate, mean = mean, sigma = sigma, n = n,
      normalizer = log(denom)
    )$value)
  
  upper <- uniroot(obj_simple, c(post_mode, post_mode + 10), post_mode, conf + (1 - conf)/2, rate, mean, sigma, n)
  lower <- uniroot(obj_simple, c(post_mode - 10, post_mode), post_mode, (1 - conf)/2, rate, mean, sigma, n)
  ci <- c(lower$root, upper$root)
  
  
  plot(xvals, yvals, type = "l")
  abline(v = ci, col = "red")
  
  return(ci)

}

```

```{r}
post_quant(.8, mean = 0, n = 300)
```
