---
title: "Understanding Distance Metric"
runtime: shiny
output: 
  html_document:
    theme: lumen
    toc: FALSE
---

```{r setup, child = '_include/setup_light.rmd'}
```


```{r, echo = FALSE}
available_distributions <- c("Cauchy", "Chi-Squared", "Exponential", 
                            "F", "Gamma", "Log-Normal", "Normal", "Student's t", 
                            "Uniform")

# Parameters for each distribution
distribution_parameters <- list(
  Cauchy = list(location = 0, scale = 1),
  "Chi-Squared" = list(df = 1, ncp = 0),  # degrees of freedom
  Exponential = list(rate = 1),
  F = list(df1 = 1, df2 = 1, ncp = 0),  # degrees of freedom
  Gamma = list(shape = 1, scale = 1),
  "Log-Normal" = list(meanlog = 0, sdlog = 1),
  Normal = list(mean = 0, sd = 1),
  "Student's t" = list(df = 1, ncp = 0),
  Uniform = list(min = 0, max = 1)
)

# Define UI
ui <- fluidPage(
  tags$head(
    tags$style(HTML("
      .parameter-box {
        border: 1px solid #ccc;
        padding: 10px;
      }
      .separator {
        margin-top: 20px;
        margin-bottom: 20px;
      }
    "))
  ),
  titlePanel("Mixture Distributions"),
  sidebarLayout(
    sidebarPanel(
      sliderInput(
        "num_mix1",
        "Select number of distributions in first mixture:",
        min = 1,
        max = 4,
        value = 2
      ),
      uiOutput("distribution_panels_mix1"),
      sliderInput(
        "num_mix2",
        "Select number of distributions in second mixture:",
        min = 1,
        max = 4,
        value = 2
      ),
      uiOutput("distribution_panels_mix2"),
      sliderInput(
        "n",
        "Number of draws per mixture:",
        min = 100,
        max = 10000,
        value = 1000,
        step = 100
      )
    ),
    mainPanel(
      fluidRow(
        column(12,
          tabsetPanel(
            tabPanel("Mixture 1", uiOutput("parameter_inputs_mix1")),
            tabPanel("Mixture 2", uiOutput("parameter_inputs_mix2"))
          )
        )
      ),
      fluidRow(
        column(12,
          div(class = "parameter-box",
            actionButton("continue_button", "Continue", class = "btn-primary")
          )
        )
      ),
      fluidRow(
        column(12,
          div(class = "separator"),
          textOutput("distance"),
          plotOutput("density_plot")
        )
      )
    )
  )
)

# Create the server function
server <- function(input, output) {
  # Generate distribution panels for mixture 1
  output$distribution_panels_mix1 <- renderUI({
    mix1_dropdowns <- lapply(1:input$num_mix1, function(i) {
      selectInput(paste0("mix1_dropdown_", i), 
                  paste0("Distribution ", i, " in first mixture:"), 
                  choices = available_distributions,
                  selected = "Normal")
    })
    
    tagList(mix1_dropdowns)
  })
  
  # Generate distribution panels for mixture 2
  output$distribution_panels_mix2 <- renderUI({
    mix2_dropdowns <- lapply(1:input$num_mix2, function(i) {
      selectInput(paste0("mix2_dropdown_", i), 
                  paste0("Distribution ", i, " in second mixture:"), 
                  choices = available_distributions,
                  selected = "Normal")
    })
    
    tagList(mix2_dropdowns)
  })
  
  # Generate parameter inputs for mixture 1
  output$parameter_inputs_mix1 <- renderUI({
    mix1_parameter_inputs <- lapply(1:input$num_mix1, function(i) {
      distribution <- input[[paste0("mix1_dropdown_", i)]]
      parameters <- distribution_parameters[[distribution]]
      parameter_inputs <- lapply(names(parameters), function(param) {
        numericInput(paste0("mix1_param_", i, "_", param),
                     paste0(param, ":"),
                     value = parameters[[param]])
      })
      
      div(class = "parameter-box",
          h4(paste0("Distribution: ", distribution)),
          fluidRow(
            column(6,
                   parameter_inputs
            ),
            column(6,
                   sliderInput(paste0("mix1_weight_", i),
                               "Weight:",
                               min = 0, max = 1, value = 0.5, step = 0.01)
            )
          )
      )
    })
    
    tagList(mix1_parameter_inputs)
  })
  
  # Generate parameter inputs for mixture 2
  output$parameter_inputs_mix2 <- renderUI({
    mix2_parameter_inputs <- lapply(1:input$num_mix2, function(i) {
      distribution <- input[[paste0("mix2_dropdown_", i)]]
      parameters <- distribution_parameters[[distribution]]
      parameter_inputs <- lapply(names(parameters), function(param) {
        numericInput(paste0("mix2_param_", i, "_", param),
                     paste0(param, ":"),
                     value = parameters[[param]])
      })
      
      div(class = "parameter-box",
          h4(paste0("Distribution: ", distribution)),
          fluidRow(
            column(6,
                   parameter_inputs
            ),
            column(6,
                   sliderInput(paste0("mix2_weight_", i),
                               "Weight:",
                               min = 0, max = 1, value = 0.5, step = 0.01)
            )
          )
      )
    })
    
    tagList(mix2_parameter_inputs)
  })
  
  # Generate the density plot when the "Continue" button is clicked
  observeEvent(input$continue_button, {
    
    mix1_data <- generate_mixture_data(input$num_mix1, "mix1", input$n)
    mix2_data <- generate_mixture_data(input$num_mix2, "mix2", input$n)
    
    output$density_plot <- renderPlot({
      
      plot_data <- rbind(mix1_data, mix2_data)
      
      plot <- ggplot(plot_data, aes(x = random_draws, fill = mixture)) +
        geom_density(alpha = 0.5) +
        theme_minimal() +
        labs(x = "Random Draws", y = "Density", title = "Mixture Distributions") +
        scale_fill_manual(values = c("#E69F00", "#56B4E9"))
      
      print(plot)
    })
    output$distance <- renderText({
      rightleft <- rlt(mix1_data$random_draws, mix2_data$random_draws)
      paste0(
        "Distance: ", round(proxy_dist(mix1_data$random_draws, mix2_data$random_draws), 3), "\n",
        "Left: ", round(rightleft[[1]], 3), " Right: ", round(rightleft[[2]], 3), " Total: ", round(rightleft[[3]], 3)
      )
    })
  })
  
  # Generate mixture data
  generate_mixture_data <- function(num_mix, mixture_name, n) {
    mixture_data <- NULL
    
    # Get weights
    weights <- lapply(1:num_mix, function(i) {
      input[[paste0(mixture_name, "_weight_", i)]]
    }) %>% unlist()
    
    # Normalize weights
    weights <- weights / sum(weights)
    
    for (i in 1:num_mix) {
      distribution <- input[[paste0(mixture_name, "_dropdown_", i)]]
      parameters <- distribution_parameters[[distribution]]
      parameter_values <- lapply(names(parameters), function(param) {
        input[[paste0(mixture_name, "_param_", i, "_", param)]]
      })
      names(parameter_values) <- names(parameters)
      
      num_draws <- round(weights[i] * n)
      
      if (distribution == "Normal") {
        random_draws <- rnorm(num_draws, mean = as.numeric(parameter_values$mean), sd = as.numeric(parameter_values$sd))
      } else if (distribution == "Exponential") {
        random_draws <- rexp(num_draws, rate = as.numeric(parameter_values$rate))
      } else if (distribution == "Chi-Squared") {
        random_draws <- rchisq(num_draws, df = as.numeric(parameter_values$df))
      } else if (distribution == "F") {
        random_draws <- rf(num_draws, df1 = as.numeric(parameter_values$df1), df2 = as.numeric(parameter_values$df2))
      } else if (distribution == "Gamma") {
        random_draws <- rgamma(num_draws, shape = as.numeric(parameter_values$shape), scale = as.numeric(parameter_values$scale))
      } else if (distribution == "Log-Normal") {
        random_draws <- rlnorm(num_draws, meanlog = as.numeric(parameter_values$meanlog), sdlog = as.numeric(parameter_values$sdlog))
      } else if (distribution == "Student's t") {
        random_draws <- rt(num_draws, df = as.numeric(parameter_values$df))
      } else if (distribution == "Uniform") {
        random_draws <- runif(num_draws, min = as.numeric(parameter_values$min), max = as.numeric(parameter_values$max))
      }
      
      mixture_data <- rbind(mixture_data, data.frame(
        distribution = distribution,
        parameters = paste0(names(parameters), " = ", unlist(parameter_values), collapse = ", "),
        random_draws = random_draws,
        mixture = mixture_name
      ))
    }
    
    mixture_data
  }
}

# Run the app
shinyApp(ui = ui, server = server)
```
