---
title: "Meeting Notes"
output:
  html_document:
    code_folding: hide
---



# Running To-Do

I need to add dates to this to do list, and maybe format it so it is cleaner... maybe a data table?

- [x] Derive normal approximation using taylor series expansion as comparison
- [x] Look at SCAD (or other paper) for example of way to rewrite the likelihood in a way that may be faster to integrate over
 - [x] Try implementing
 - [ ] Revisit to figure out what is causing errors
- [x] Consider the speed at which the bootstrap works when considering other methods
- [ ] Read paper mentioned about gaussian mirrors 
- [ ] Look at univariate example when Beta is very small, say, beta = .01
- [ ] Profile code to see what is expensive in the bayesian bootstrap
- [x] Update code with normalization constant on the log scale
- [ ] Find a way to cleanly present the plots, maybe make ggplotly instead?
- [ ] Look into variational bayes (again) for lasso, or generally if someone has tried to approximate the lasso posterior (numerically or annalytically)
- [ ] Create mre for "Error: Supplied lambda value(s) are outside the range of the model fit."
- [x] Look into bridge sampling
  - Seems more like a method to compute the marginal likelihood which doesn't seem directly relevant for the current context since we really need to get directly at the posterior
- [x] Work on simple versions first before trying to extend it to more complex cases.
  - [x] Need to test current on simpler version
- [x] Look at visualizing the prior / posterior (Do with original interval finding method)
- [x] Consider integrating from posterior mode (lasso solution)
 - This turned out to be not great when skewed
- [x] Move denominator into log to see if that would help
  - Didn't have an noticeable improvement
- [x] Clean up three methods of interval finding
  - Done for now, will stick with simpler of the three and in the future look back at the hpd method
- [x] Create "non-normalized" versions of plots
  - Doesn't seem viable as this causes plots to essentially be meaningless

# Week of Monday, September 4th, 2023

- SNR not working as expected?


# August 16th, 2023

## To Discuss

- Worked on updating the interval finding function to be more stable but continued running into issues. I really think this stems back to instability in computing the proportionality constant. I have made some progress and currently believe that as long as I can find a constant such that I am then able to compute a non-zero / non-infinite value for the density at the posterior mode that this method should work.
- I looked down the path of "Determining Bayes Normalizing Constant" but aside from instability in the estimation of this quantity, I think there is just an issue in general with it being so small. I'm not sure any method I develop that requires a similar approach will be fruitful. Which is why I believe my approach alluded to in the first point is necessary first.
- I also saw issues arising from skewed posteriors which make finding density from the posterior mode potentially have issues, but these could also stem back to the earlier point made. I think this method would be potentially the most stable option but everything relies heavily on computing that normalizing constant.
  - I also worked on a method to find the HPD, but again, it is little use with methods with the normalizing constant issue. However, given recent discoveries I want to revisit this in the future.
- I read "Analytic solution and stationary phase approximation for the Bayesian lasso and elastic net." This honestly fits perfectly into what we would need except for the fact that it does not work for lasso when the design matrix is rank deficient. This also concerns me because the paper is not too old (late 2018) suggesting to me that other analytic solutions (i.e. variational Bayes) may not exist for the lasso.
- Potential papers for variational Bayes:
  - Variational Full Bayes Lasso: Knots Selection in Regression Splines (https://arxiv.org/pdf/2102.13548v1.pdf)

## Action Items

- Derive normal approximation through taylor series expansion as comparison
- Look at SCAD (or other paper) for example of way to rewrite the likelihood in a way that may be faster to integrate over
 - Try implimenting
- Consider the speed at which the bootstrap works when considering other methods
- Read paper mentioned about gaussian mirrors (ask patrick if can't find)
- Look at univariate example when Beta is very small, say, beta = .01
- Profile code to see what is expensive

# July 26th, 2023

## To Discuss

- Initial results from "Simple Empirical Bayes Bootstrapped Confidence Intervals"
  - The results look bizarre, particularly for variables with zero as the true coefficient.
- Efficient Empirical Bayes Variable Selection and Estimation in Linear Models
  - The paper suggests a method in which under specific conditions the Lasso can be used as a computational short cut for model selection / estimation using a specific hierarchical prior for a linear model. With this, the authors also propose a way to select lambda and estimate $\sigma^2$ (and hence obtaining the final model as the lasso solution).
- Would we like to set up a drop box to store data objects?

## Notes

- Need to do a better job at taking notes during meeting

## Action Items

- See to do above. Need to do better next time separating general discussion notes and what I need to work on going forward.

